## CHANGE this to the name of your plugin.
name: SFDrugs

## CHANGE this to your username.
author: cworldstar

## CHANGE this to a meaninful but short description of your plugin.
description: Adds drugs to Slimefun4

## CHANGE this to the path of the class that extends JavaPlugin.
main: me.cworldstar.sfdrugs.SFDrugs

## You can change this to link to your website or repository. You can also remove this line if you want to.
website: https://github.com/Sniperkaos/SFIllegalActivities

## This value is automatically replaced by the version specified in your pom.xml file.
## Do not change this.
version: ${project.version}

## This is the minimum minecraft version required to run your plugin.
api-version: 1.19

## This is required and marks Slimefun as a plugin dependency.
depend:
  - Slimefun
softdepend:
  - InfinityExpansion
  - WorldEdit
  - FastAsyncWorldEdit

commands:
  test:
    description: Test boss fights.
    usage: /<command>
    permission: sfdrugs.dev.test
  give_upgrade:
    description: give upgrade
    usage: /<command>
    permission: sfdrugs.dev.give_upgrade
  refresh_trader:
    description: refreshes trader
    usage: /<command> <trader/all>
    permission: sfdrugs.dev.refresh_trader