package me.cworldstar.sfdrugs.utils;

public class Constants {
    public static final String SfDrugsIsCorporationTrader = "SFDRUGS_IS_CORPORATION_TRADER";
    public static final String SfDrugsPlayerIsRightClickingTrader = "SFDRUGS_PLAYER_IS_RIGHTCLICKING_TRADER";
    public static final String naniteSynthesizer_maxX = "naniteSynthesizer.maxX";
    public static final String naniteSynthesizer_maxZ = "naniteSynthesizer.maxZ";
    public static final String corporate_building_schem = "corporate_building.schem";
    public static final String WorldEdit = "WorldEdit";
    public static final String FastAsyncWorldEdit = "FastAsyncWorldEdit";
    public static final String schematics = "schematics";
    public static final String HookerZombie = "&d&lHooker Zombie";
    public static final String SfDrugsCustomMob = "SFDRUGS_CUSTOM_MOB";
    public static final String red_wolves_trainee = "red_wolves_trainee";
    public static final String corporate_security_robot = "corporate_security_robot";
    public static final String escaped_test_subject = "escaped_test_subject";
    public static final String red_wolves_gangster = "red_wolves_gangster";
    public static final String SfDrugsIsLaserProjectile = "SFDRUGS_IS_LASER_PROJECTILE";
    public static final String AfflictedBySfDrugsRobotArmor = "AFFLICTED_BY_SFDRUGS_ROBOT_ARMOR";
    public static final String CorporateSecurityRobot = "Corporate Security Robot";
    public static final String corporate_dimension = "corporate_dimension";
    public static final String spawn_corporate_building = "spawn_corporate_building";
    public static final String SfDrugsIsHooker = "SFDRUGS_IS_HOOKER";
    public static final String hooker_zombie = "hooker_zombie";
    public static final String Unstable = "Unstable";
    public static final String CorporateWorker = "CORPORATE_WORKER";
    public static final String Upgrade = "Upgrade";
    public static final String schem = "schem";
    public static final String corporate_leader = "corporate_leader";
    public static final String corporate_executive = "corporate_executive";
    public static final String corporate_greeter = "corporate_greeter";
    public static final String corporate_scout = "corporate_scout";
    public static final String cs_head_1 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgxOWM5OTY2ZmQ4OWI0YjM4MTJlMmRmMTdkODk4NzliZTVmMjNmZGU5ZmQ3MTQ2NWQzZjAwMjM2ZGJkMjZmOCJ9fX0=";
    public static final String cw_head_1 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgxOWM5OTY2ZmQ4OWI0YjM4MTJlMmRmMTdkODk4NzliZTVmMjNmZGU5ZmQ3MTQ2NWQzZjAwMjM2ZGJkMjZmOCJ9fX0=";
    public static final String corporate_worker = "corporate_worker";
    public static final String ets_head_1 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvYWNjNGI1YjdmNjE2OTQyOGNlZTcyZDFkZTNlYjkzNTc5M2I3ZDZmNGI2YzFhMjNjMzRhMjZkZGE2MDYwMWNjOSJ9fX0=";
    public static final String gm_head_1 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjc2MzQzZjU3NzYwMTY3ODNjMDJmZTdiNDU3NjMxYWU2YWJjZWIwMjYzOTQwODBhZmNjMzM1NDIxYjJjYzZiIn19fQ==";
    public static final String sgm_head_1 = "eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjgxOWM5OTY2ZmQ4OWI0YjM4MTJlMmRmMTdkODk4NzliZTVmMjNmZGU5ZmQ3MTQ2NWQzZjAwMjM2ZGJkMjZmOCJ9fX0=";
    public static final String all = "all";
    public static final String inventory = "inventory";
    public static final String fix_drug = "fix_drug";
    public static final String methamphetamine_overdosing = "methamphetamine_overdosing";
    public static final String generate = "generate";
    public static final String getposinchunk = "getposinchunk";
    public static final String sm_output = "sm output";
    public static final String dark_matter_machine = "dark-matter-machine";
    public static final String dark_matter_amount = "dark-matter-amount";
    public static final String dark_matter_generator = "dark-matter-generator";
    public static final String dark_matter_transmitter = "dark-matter-transmitter";
    public static final String tti_border = "tti_border";
    public static final String tti_input = "tti_input";
    public static final String tti_output = "tti_output";
    public static final String SfDrugsArmorHealthBonus = "SFDRUGS_ARMOR_HEALTH_BONUS";
    public static final String Charges = "Charges";
    public static final String SfDrugsDrugSet = "SFDRUGS_DRUGSET";
    public static final String SfDrugsPlatedHazmat = "SFDRUGS_PLATED_HAZMAT";
    public static final String power_armor_base = "power_armor_base";
    public static final String power_armor_core = "power_armor_core";
    public static final String TraderTag = "TraderTag";
    public static final String corporation_trader = "corporation_trader";
    public static final String mysterious_trader = "mysterious_trader";
    public static final String _overdosing = "_overdosing";
    public static final String _overdose = "_overdose";
    public static final String SfDrugsIsMysteriousTrader = "SFDRUGS_IS_MYSTERIOUS_TRADER";
    public static final String SfDrugsCorporationEnemy = "SFDRUGS_CORPORATIONENEMY";
    public static final String cd = "Cooldown";
    public static final String sgm = "SmallerGangMember";
}
